# dtype 데이터형 확인 (Python 3.6.7 실행)


**numpy에서 사용되는 자료형 종류**

(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미)

부호가 있는 정수 int(8, 16, 32, 64)

부호가 없는 정수 uint(8 ,16, 32, 54)

실수 float(16, 32, 64, 128)

복소수 complex(64, 128, 256)

In [1]:
import numpy as np

In [2]:
# array 자료형 확인 
a = np.array([1, 3, 5, 7, 9])
a.dtype

dtype('int64')

In [3]:
b = np.array([-1, -3, -5, -7, -9], np.int16)
b.dtype

dtype('int16')

In [4]:
c= np.array([1, 3, 5, 7, 9], np.uint16)
c.dtype

dtype('uint16')

In [5]:
d= np.array([1,2,3,3.5,4])
d.dtype

dtype('float64')

In [6]:
e = np.array(2.718281828459045 + 3.141592653589793j, np.complex64)
e.dtype

dtype('complex64')

# Iterating (배열 반복)

1D Array

In [7]:
x = np.arange(11)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
# Python의 for 반복문 이용
for i in x:
    print(i)

0
1
4
9
16
25
36
49
64
81
100


2D Array

n차원 배열의 각각의 개별 요소 접근 방법 3가지
1. 차원 수 만큼의 중첩 for문 이용해 접근
2. reshape(-1)로 평탄화 (1차원 배열 생성) 후 접근
3. nditer() 함수로 다차원 배열의 원소(스칼라)에 바로 접근 가능

In [9]:
x = np.arange(10, 22).reshape(3, 4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [10]:
# Python의 for 반복문. 중첩 없을 경우
for row in x:
        print(row)

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [11]:
# n차원 배열일 경우, n-1 차원이 for 반복문을 각각 통과함
for row in x:
        for i in row:
            print(i)

10
11
12
13
14
15
16
17
18
19
20
21


In [12]:
# reshape(-1)로 평탄화
newX = x.reshape(-1)
for row in newX:
        print(row)

10
11
12
13
14
15
16
17
18
19
20
21


In [13]:
# nditer()
for i in np.nditer(x):
  print(i)

10
11
12
13
14
15
16
17
18
19
20
21


nditer() 응용 - 다른 dtype의 array 반복

> np.nditer(arr, flags=['buffered'], op_dtypes=['data_type'])

arr: 배열

flags=['buffered']: 데이터타입 변환을 위해 필요한 버퍼 공간(option)

op_dtypes=['data_type']: 변환하고자 하는 데이터 타입(option)

In [14]:
# 정수 타입 → 문자열 타입) 변환 후, 접근
x = np.array([1, 2, 3])

for i in np.nditer(x, flags=['buffered'], op_dtypes=['S']):

  print(i)

b'1'
b'2'
b'3'


nditer() 응용 - 다른 step으로 일부 요소만 array 반복 

1차원의 각 차원에 대해 1씩 증가하게 색인 후, 

2차원의 각 요소를 2씩 증가하게 색인하여 선택함



In [15]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(x[:, ::2]):

  print(i)

1
3
5
7
