# Array Indexing,  Slicing

Numpy에서 사용되는 Indexing과  Slicing은 기본적으로 Python 과 동일

주의할 점은, Python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작함


In [1]:
import numpy as np

1D Array

In [2]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1[1]

1

In [4]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [5]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
arr1[-1:]

array([9])

2D Array

In [8]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 2차원 array인덱싱을 위해선 2개 인자 입력 필요
arr2[0,0]

1

In [10]:
arr2[2,:] # 2행의 모든 요소 꺼내기

array([ 9, 10, 11, 12])

In [11]:
arr2[:,3] # 모든 행의 3번째 요소 꺼내기

array([ 4,  8, 12])

In [12]:
arr2[-1:]

array([[ 9, 10, 11, 12]])

In [13]:
arr2[-2:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2[-3:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr2[1:-1]

array([[5, 6, 7, 8]])

# Array boolean Indexing(mask)
위에서 이용한 다차원의 Indexing을 응용하여 boolean Indexing 가능

해당 기능은 주로 mask라고 이야기하는데, boolean Indexing을 통해 만들어낸 array를 

원하는 행 또는 열의 값만 쉽게 필터링 해 추출할 수 있다

즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.


In [16]:
names = np.array(['Kim','Kim','Lee','Park','Yun','Kim','Park','Kim'])
names 
# 문자열 Numpy arrat는 출력시 dtype='<U(최대 문자열 길이) 같이 출력

array(['Kim', 'Kim', 'Lee', 'Park', 'Yun', 'Kim', 'Park', 'Kim'],
      dtype='<U4')

In [17]:
names.shape

(8,)

In [18]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재함
data = np.random.randn(8,4)
data

array([[ 0.22149424, -0.37195133, -0.92915665, -0.14619366],
       [ 0.12556883,  0.29102078,  0.07550725,  1.30457518],
       [ 1.04277429, -0.31610364, -1.2673502 ,  1.06518214],
       [-0.94846972, -0.10954192, -0.36397832,  0.41769068],
       [-1.58084661,  1.3484981 , -0.87232785,  1.12538683],
       [-1.6769463 , -0.31895902, -0.86509253, -0.38875714],
       [ 0.62057808,  1.49657712, -1.16760124, -0.9744188 ],
       [-1.60182669, -0.37510781,  0.99510391, -1.86692746]])

In [19]:
data.shape

(8, 4)

위의 names의 각 요소가 data의 각 행과 연결된다 가정하고

names의 'Kim'인 행의 data만 보고싶을 때 마스크 사용

In [20]:
# 요소가 Kim인 행의 데이터만 꺼내기
names_Kim_mask = (names == 'Kim')
names_Kim_mask 

array([ True,  True, False, False, False,  True, False,  True])

In [21]:
data[names_Kim_mask,:] # 변수명 뒤에(,)과(:) 붙여 사용
# Kim은 0,1,5,7행에 위치하므로 0,1,5,7행의 모든 요소 꺼내옴

array([[ 0.22149424, -0.37195133, -0.92915665, -0.14619366],
       [ 0.12556883,  0.29102078,  0.07550725,  1.30457518],
       [-1.6769463 , -0.31895902, -0.86509253, -0.38875714],
       [-1.60182669, -0.37510781,  0.99510391, -1.86692746]])

In [22]:
# 요소가 Yun인 행의 데이터만 꺼내기
data[names == 'Yun',:]

array([[-1.58084661,  1.3484981 , -0.87232785,  1.12538683]])

In [23]:
# 논리 연산을 응용하여, 요소가 Park또는 Yun 인 행의 데이터만 꺼내기
data[(names == 'Park') | (names == 'Yun'),:]


array([[-0.94846972, -0.10954192, -0.36397832,  0.41769068],
       [-1.58084661,  1.3484981 , -0.87232785,  1.12538683],
       [ 0.62057808,  1.49657712, -1.16760124, -0.9744188 ]])

data array 자체적으로도 마스크를 만들고, 이를 응용하여 Indexing가능
data array에서 0번째 열의 값이 0보다 작은 행을 구하기

In [24]:
# 먼저 마스크 생성
# data array에서 0번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다 -> 6인덱스 하나
data[:,0] < 0

array([False, False, False,  True,  True,  True, False,  True])

In [25]:
# 위에서 만든 마스크를 이용하여 data의 0번째 열의 값이 0보다 작은 행을 구한다
data[data[:,0]<0,:]
# 이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.

array([[-0.94846972, -0.10954192, -0.36397832,  0.41769068],
       [-1.58084661,  1.3484981 , -0.87232785,  1.12538683],
       [-1.6769463 , -0.31895902, -0.86509253, -0.38875714],
       [-1.60182669, -0.37510781,  0.99510391, -1.86692746]])

In [26]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값 변경
data[data[:,0]<0,2:4]

array([[-0.36397832,  0.41769068],
       [-0.87232785,  1.12538683],
       [-0.86509253, -0.38875714],
       [ 0.99510391, -1.86692746]])

In [27]:
data[data[:,0]<0,2:4] = 0
data

array([[ 0.22149424, -0.37195133, -0.92915665, -0.14619366],
       [ 0.12556883,  0.29102078,  0.07550725,  1.30457518],
       [ 1.04277429, -0.31610364, -1.2673502 ,  1.06518214],
       [-0.94846972, -0.10954192,  0.        ,  0.        ],
       [-1.58084661,  1.3484981 ,  0.        ,  0.        ],
       [-1.6769463 , -0.31895902,  0.        ,  0.        ],
       [ 0.62057808,  1.49657712, -1.16760124, -0.9744188 ],
       [-1.60182669, -0.37510781,  0.        ,  0.        ]])