# Basic Math Operations

Array의 기본 연산은 같은 위치의 각 원소간에 연산이다


In [2]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([[6, 5, 4], [3, 2, 1]])
b

array([[6, 5, 4],
       [3, 2, 1]])

In [ ]:
# +
a + b

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# -
a - b

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [ ]:
# *
a * b

array([[ 6, 10, 12],
       [12, 10,  6]])

In [ ]:
# /
a / b

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

In [ ]:
# **
a ** b

array([[ 1, 32, 81],
       [64, 25,  6]])

In [ ]:
# //
a // b

array([[0, 0, 0],
       [1, 2, 6]])

In [ ]:
# %
a % b

array([[1, 2, 3],
       [1, 1, 0]])

# Broadcasting
array의 브로드 캐스트는
위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,

numpy에서는 브로드캐스트라는 기능을 제공

브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것

서로 크기가 다른 arr1과 arr3의 연산이 가능



이때, 연산은 각 array의 같은 인덱스 위치의 요소간 연산값 출력


아래 예제의 연산결과를 살펴보면 

arr3이 [7,8,9] 에서 [[7,8,9],[7,8,9]]로 확장되어 계산되었음을 확인할 수 있음


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3 = np.array([7,8,9])
print(arr3)
print(arr3.shape)

[7 8 9]
(3,)


In [ ]:
arr1 + arr3

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
arr1 - arr3

array([[-6, -6, -6],
       [-3, -3, -3]])

In [ ]:
arr1 * arr3

array([[ 7, 16, 27],
       [28, 40, 54]])

하나의 array에 스칼라 연산도 가능

In [ ]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]])

# Matrix Multiplication

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [ ]:
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [ ]:
d = np.matmul(a,b)
d

array([[19, 22],
       [43, 50]])

In [ ]:
e = np.dot(a, b)
e

array([[19, 22],
       [43, 50]])

In [ ]:
f = a.dot(b)
f

array([[19, 22],
       [43, 50]])

# Inner Product

In [ ]:
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [ ]:
c = np.matmul(a, b)
c

array([[19, 22],
       [43, 50]])

In [ ]:
d = np.dot(a, b)
d

array([[19, 22],
       [43, 50]])

In [ ]:
e = a.dot(b)
e

array([[19, 22],
       [43, 50]])

# Square, Square Root

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
y = np.square(x)
y

array([ 1,  4,  9, 16])

In [ ]:
z = np.sqrt(x)
z

array([1.        , 1.41421356, 1.73205081, 2.        ])

# Sum

In [3]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
x.sum()

10

In [ ]:
np.sum(x)

10

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
b = a.sum()
b

21

In [ ]:
c = a.sum(axis=0)
c

array([5, 7, 9])

In [ ]:
e = a.sum(axis=1)
e

array([ 6, 15])

# Cumulative Sum

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [17]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [37]:
a = np.arange(12).reshape(3, 4)

In [38]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [39]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [40]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Product

In [ ]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [4]:
x.prod()

24

In [5]:
np.prod(x)

24

In [6]:
np.product(x)

24

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
x.prod()

720

In [12]:
x.prod(axis=0)

array([ 4, 10, 18])

In [13]:
x.prod(axis=1)

array([  6, 120])

# Cumulative Product

In [42]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [43]:
a.cumprod()

array([0, 0, 0, 0, 0, 0])

In [44]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0])

In [45]:
a = np.arange(1, 10).reshape(3, 3)

In [46]:
a.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [47]:
a.cumprod(axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]])

In [48]:
a.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

# amin, amax

In [49]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [50]:
a.min()

0

In [51]:
np.min(a)

0

In [52]:
np.amin(a)

0

In [53]:
a.max()

5

In [54]:
np.max(a)

5

In [55]:
np.amax(a)

5

In [56]:
a = np.arange(1, 10).reshape(3, 3)

In [57]:
a.min(axis=0)

array([1, 2, 3])

In [58]:
a.min(axis=1)

array([1, 4, 7])

In [59]:
a.max(axis=1)

array([3, 6, 9])

# fmin, fmax

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.array([[6, 5, 4], [3, 2, 1]])
b

array([[6, 5, 4],
       [3, 2, 1]])

In [5]:
np.fmin(a, b)

array([[1, 2, 3],
       [3, 2, 1]])

In [6]:
np.minimum(a, b)

array([[1, 2, 3],
       [3, 2, 1]])

In [7]:
np.fmax(a, b)

array([[6, 5, 4],
       [4, 5, 6]])

In [8]:
np.maximum(a, b)

array([[6, 5, 4],
       [4, 5, 6]])

# Mean

In [9]:
a = np.array([1, 2, 3, 4])

In [10]:
a.mean()

2.5

In [11]:
np.mean(a)

2.5

In [12]:
np.average(a)

2.5

In [13]:
a = np.array([[1, 2], [3, 4]])

In [14]:
a.mean()

2.5

In [15]:
a.mean(axis=0)

array([2., 3.])

In [16]:
a.mean(axis=1)

array([1.5, 3.5])

# Weighted Average

In [17]:
x = np.array([1, 2, 3, 4])
w = np.array([3, 3, 2, 1])

In [18]:
np.average(x, weights=w)

2.111111111111111

In [19]:
(w*x).sum() / w.sum()

2.111111111111111

# Variance, Standard Deviation

In [20]:
x = np.array([1, 2, 3, 4])

In [21]:
x.var()

1.25

In [22]:
np.var(x)

1.25

In [23]:
x.std()

1.118033988749895

In [24]:
np.std(x)

1.118033988749895