# Array Operations 

zeros()

ones()

full()

empty()

zeros_like()

ones_like()

full_like()

empty_like()

fromfunction()

In [1]:
import numpy as np


# zeros

인자로 받는 크기만큼, 모든 요소가 0인 Array 생성

In [2]:
a = np.zeros(10)
print(a, a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ones

인자로 받는 크기만큼, 모든 요소가 1인 Array 생성

In [5]:
a = np.ones(7)
print(a, a.dtype)

[1. 1. 1. 1. 1. 1. 1.] float64


In [6]:
a = np.ones((2,5))
print(a, a.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64


#  full

지정된 모양의, 입력한 값으로만 채워진 Array 생성



In [11]:
a = np.full(5, 7) # 첫번째 인자로 크기, 두번째 인자가 값
print(a, a.dtype)

[7 7 7 7 7] int64


In [9]:
a = np.full(5, 3.14)
print(a, a.dtype)

[3.14 3.14 3.14 3.14 3.14] float64


In [13]:
a = np.full((3, 5), 3.14) 
print(a, a.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] float64


# empty

지정된 모양의 Array 생성

각 원소는 '초기화되지않은 값'으로 채워짐

for문을 사용하여 배열의 각 요소에 단일 값을 할당하여 사용

In [32]:
a = np.empty(5) 

for i in range(5):
    a[i] = 7 # 각 원소를 7로 채워줌
print(a)

[7. 7. 7. 7. 7.]


In [38]:
b = np.empty((3, 4))
print(b, b.dtype)
# 7로 채워진 이유는 앞의 연산에서 초기화되지 않은 값이기때문

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]] float64


# zeros_like

Array의 shape 크기만큼 0값으로 채워 Array 반환

In [39]:
a = np.array([1, 3, 5, 7, 9])

In [40]:
b = np.zeros_like(a) # 원래 값 대신 0으로 채워져 반환
print(b, b.dtype)

[0 0 0 0 0] int64


In [41]:
a = np.array([1.41, 2.72, 3.14])
b = np.zeros_like(a)
print(b, b.dtype) # 값은 변해도 type은 그대로 상속 받음

[0. 0. 0.] float64


In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [43]:
b = np.zeros_like(a)
print(b, b.dtype)

[[0 0 0]
 [0 0 0]] int64


# ones_like

Array의 shape 크기만큼 1값으로 채워 Array 반환

In [44]:
a = np.array([1, 3, 5, 7, 9])

In [45]:
b = np.ones_like(a)
b

array([1, 1, 1, 1, 1])

In [46]:
a = np.array([1.41, 2.72, 3.14])

In [47]:
b = np.ones_like(a)
b

array([1., 1., 1.])

In [48]:
b = np.ones_like(a, dtype=np.int64)
b

array([1, 1, 1])

In [49]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
b = np.ones_like(a)

# full_like

Array의 shape 크기만큼 0값으로 채워 Array 반환

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [52]:
b = np.full_like(a, 7) # 채울 값을 7로 설정
b

array([[7, 7, 7],
       [7, 7, 7]])

In [54]:
b = np.full_like(a, 7, dtype=np.float64)
b

array([[7., 7., 7.],
       [7., 7., 7.]])

In [55]:
a = np.array([1.41, 2.72, 3.14])

In [58]:
b = np.full_like(a, 5)
b

array([5., 5., 5.])

In [59]:
b = np.full_like(a, 5, dtype=np.int64)
b

array([5, 5, 5])

# empty_like

Array의 shape 크기만큼 초기화되지 않은 값으로 채워 Array 반환

In [62]:
a = np.array([1, 3, 5])
a

array([1, 3, 5])

In [69]:
b = np.empty_like(a) 
b # a의 형태를 따르나 쓰레기값으로 채워져있음

array([2.80651895e-316, 6.18604229e+223, 6.21435204e-310])

In [66]:
a = np.array([1.41, 2.72, 3.14])

In [67]:
b = np.empty_like(a)
b

array([2.80651895e-316, 6.18604229e+223, 6.21435204e-310])

In [71]:
b = np.empty_like(a, dtype=np.int64)
b

array([           56804576, 7954874581515239424,     125779885582708])

In [72]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [73]:
b = np.empty_like(a)
b

array([[4619567317775286272, 4619567317775286272, 4619567317775286272],
       [4619567317775286272, 4619567317775286272, 4619567317775286272]])

In [76]:
b = np.empty_like(a, dtype=np.float64)

for i in range(2):
    b[i] = 8 # 각 원소값을 8로 지정
print(b)

[[8. 8. 8.]
 [8. 8. 8.]]
