# arithmetic operator

Array의 산술 연산은 같은 위치의 각 원소간 연산이 이루어짐


In [1]:
import numpy as np

In [97]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b = np.array([[6, 5, 4], [3, 2, 1]])
b

array([[6, 5, 4],
       [3, 2, 1]])

In [4]:
# +
a + b

array([[7, 7, 7],
       [7, 7, 7]])

In [5]:
# -
a - b

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [6]:
# *
a * b

array([[ 6, 10, 12],
       [12, 10,  6]])

In [7]:
# /
a / b

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

In [8]:
# **
a ** b

array([[ 1, 32, 81],
       [64, 25,  6]])

In [99]:
# // 몫
a // b

array([[0, 0, 0],
       [1, 2, 6]])

In [100]:
# % 나머지
a % b

array([[1, 2, 3],
       [1, 1, 0]])

하나의 array에 스칼라 연산도 가능

In [102]:
a * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [103]:
a **2

array([[ 1,  4,  9],
       [16, 25, 36]])

# Broadcasting

일반적으로 array가 같은 크기를 가져야만 서로 연산이 가능하지만,

numpy에서 제공하는 브로드캐스트 기능을 통해 서로 크기가 다른 array간 연산이 가능하다

아래 예제를 보면

서로 크기가 다른 arr1과 arr2의 연산이 가능

이때, 연산은 각 array의 같은 인덱스 위치의 요소간 연산값 출력
 
arr3이 [7,8,9] 에서 [[7,8,9],[7,8,9]]로 확장되어 계산되었음을 확인할 수 있음


In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr2 = np.array([7,8,9])
arr2

array([7, 8, 9])

In [105]:
arr1 + arr2

array([[ 8, 10, 12],
       [11, 13, 15]])

In [106]:
arr1 - arr2

array([[-6, -6, -6],
       [-3, -3, -3]])

In [107]:
arr1 * arr2

array([[ 7, 16, 27],
       [28, 40, 54]])

# Matrix Multiplication

행렬곱 연산


In [116]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [117]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])


행렬곱은 다른 연산과 달리 같은 위치의 원소간 연산이 아님

Array a와 b를 곱할 경우, a의 해당 위치가 속한 열과

b의 해당 위치가 속한 행 단위로 연산이 이루어짐

a @ b 의 경우

(1 x 5) + (2 x 7) = 5 + 14 = 19 

(1 x 6) + (2 x 8) = 22

(3 x 5) + (4 x 7) = 43

(3 x 6) + (4 x 8) = 50

In [119]:
# @ 연산자는 ver 3.5 이상에서만 가능
c = a @ b 
c

array([[19, 22],
       [43, 50]])

In [120]:
# np.matmul
d = np.matmul(a,b)
d

array([[19, 22],
       [43, 50]])

In [121]:
# np.dot
e = np.dot(a, b) #  a.dot(b)와 동일
e

array([[19, 22],
       [43, 50]])

# Inner Product

벡터 내적

열벡터인 두개의 벡터 a,b가 주어졌을때, a를 전치해서 b를 곱하는 것

x를 전치해서 y를 곱하거나 반대의 경우도 값이 같음

결과값은 스칼라 형태

In [124]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [125]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [126]:
c = a @ b
c

32

In [127]:
c = np.matmul(a, b)
c

32

In [128]:
d = np.dot(a, b)
d

32

In [28]:
e = a.dot(b)
e

array([[19, 22],
       [43, 50]])

# Square
배열 원소의 제곱값(square value) 반환

# Square Root
배열 원소의 제곱근(Square Root) 반환

In [29]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [129]:
y = np.square(x)
y

array([ 1,  4,  9, 16])

In [130]:
z = np.sqrt(x)
z

array([1.        , 1.41421356, 1.73205081, 2.        ])

# Sum

배열 원소 간 합 반환

In [131]:
# 1D Array
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [133]:
x.sum() # 1 + 2 + 3 + 4 = 10

10

In [34]:
np.sum(x)

10

In [134]:
# 2D Array
a = np.array([[1, 2, 3], [4, 5, 6]])

In [136]:
b = a.sum() # 전체 원소 합 반환
b

21

In [137]:
c = a.sum(axis=0) # 행간 덧셈. 결과값의 원소수는 행의 수와 동일
c

array([5, 7, 9])

In [138]:
e = a.sum(axis=1)# 열간 덧셈. 결과값의 원소수는 열의 수와 동일
e

array([ 6, 15])

# Cumulative Sum

배열에서 주어진 축에 따라 누적되는 원소들의 누적 합 반환

In [139]:
# 1D Array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [141]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [144]:
# 2D Array
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
a.cumsum() # 전체 원소 누적합 반환

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [148]:
a.cumsum(axis=0) # 같은 행 끼리의 누적 합

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [149]:
a.cumsum(axis=1)  # 같은 열 끼리의 누적 합

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Product

주어진 축에서 배열 요소의 곱을 반환

In [46]:
# 1D Array
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [150]:
x.prod() # 1 * 2 * 3 * 4 = 24

24

In [48]:
np.prod(x)

24

In [49]:
np.product(x)

24

In [156]:
# 2D Array
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
x.prod() # 전체 원소곱 반환

720

In [158]:
x.prod(axis=0) # 같은 행 끼리의 곱

array([ 4, 10, 18])

In [159]:
x.prod(axis=1)# 같은 열 끼리의 곱

array([  6, 120])

# Cumulative Product

In [167]:
# 1D Array
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [168]:
a.cumprod()

array([  1,   2,   6,  24, 120])

In [169]:
np.cumprod(a)

array([  1,   2,   6,  24, 120])

In [175]:
# 2D Array
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
a.cumprod() # 전체 원소 누적곱 반환

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [176]:
a.cumprod(axis=0) # 같은 행 끼리의 누적곱

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]])

In [177]:
a.cumprod(axis=1) # 같은 열 끼리의 누적곱

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

# amin, amax

배열의 최소/최댓값 또는 축의 최소/최댓값 반환

np.amin은 Array의 최솟값을 반환해주며

내 생각엔 np.min과 np.amin의 기능상 차이는 없는 것 같다. 

np.min도 axis 설정 가능함

In [180]:
# 1D Array
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [184]:
a.min()

1

In [185]:
np.min(a)

1

In [186]:
np.amin(a)

1

In [187]:
a.max()

5

In [188]:
np.max(a)

5

In [189]:
np.amax(a)

5

In [191]:
# 2D Array
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
a.min(axis=0) # 각 행에서 최솟값을 원소로 가지는 배열

array([1, 2, 3])

In [193]:
a.min(axis=1)# 각 열에서 최솟값을 원소로 가지는 배열

array([1, 4, 7])

In [194]:
a.max(axis=1)# 각 열에서 최댓값을 원소로 가지는 배열

array([3, 6, 9])

# fmin, fmax

인자로 받은 두 배열을 비교하고 요소 별 최소/최댓값을 가진 새 배열 반환

In [195]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
b = np.array([[3, 2, 1], [6, 5, 4]])
b

array([[3, 2, 1],
       [6, 5, 4]])

In [202]:
np.fmin(a, b) # 같은 위치의 원소 중 더 작은 값을 원소로 가짐

array([[1, 2, 1],
       [4, 5, 4]])

In [203]:
np.minimum(a, b)

array([[1, 2, 1],
       [4, 5, 4]])

In [204]:
np.fmax(a, b)

array([[3, 2, 3],
       [6, 5, 6]])

In [205]:
np.maximum(a, b)

array([[3, 2, 3],
       [6, 5, 6]])

# Mean

평균 반환

In [206]:
# 1D Array
a = np.array([1, 2, 3, 4])

In [207]:
a.mean()

2.5

In [208]:
np.mean(a)

2.5

In [209]:
np.average(a)

2.5

In [211]:
# 2D Array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [212]:
a.mean() # 전체 원소의 평균 반환

2.5

In [213]:
a.mean(axis=0) # 각 열의 평균 반환

array([2., 3.])

In [214]:
a.mean(axis=1) # 각 행의 평균 반환

array([1.5, 3.5])

# Weighted Average

배열의 가중 평균 반환

In [218]:
x = np.array([1, 2, 3, 4]) 
x

array([1, 2, 3, 4])

In [219]:
w = np.array([3, 3, 2, 1]) # 가중치
w

array([3, 3, 2, 1])

x원소에 가중치를 곱한 값 = (1 x 3) + (2 x 3) + (3 x 2) + (4 x 1) = 19

가중치 w의 전체 합 = 9

x 가중 평균 = 19 / 9 = 2.11111111111

In [221]:
np.average(x, weights=w) # x에 w라는 가중치를 주어 평균을 구한 것

2.111111111111111

In [88]:
(w*x).sum() / w.sum()

2.111111111111111

# Variance, Standard Deviation

분산과 표준편차 반환

In [223]:
x = np.array([1, 2, 3, 4])

In [228]:
# 분산
x.var()

1.25

In [225]:
np.var(x)

1.25

In [229]:
# 표준편차
x.std()

1.118033988749895

In [227]:
np.std(x)

1.118033988749895