# Array Operations 

zeros()

ones()

full()

empty()

zeros_like()

ones_like()

full_like()

empty_like()

fromfunction()

In [1]:
import numpy as np


# zeros

인자로 받는 크기만큼, 모든 요소가 0인 Array 생성

In [2]:
a = np.zeros(10)
print(a, a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ones

인자로 받는 크기만큼, 모든 요소가 1인 Array 생성

In [4]:
a = np.ones(7)
print(a, a.dtype)

[1. 1. 1. 1. 1. 1. 1.] float64


In [5]:
a = np.ones((2,5))
print(a, a.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64


#  full

지정된 모양의, 입력한 값으로만 채워진 Array 생성



In [6]:
a = np.full(5, 7) # 첫번째 인자로 크기, 두번째 인자가 값
print(a, a.dtype)

[7 7 7 7 7] int64


In [7]:
a = np.full(5, 3.14)
print(a, a.dtype)

[3.14 3.14 3.14 3.14 3.14] float64


In [8]:
a = np.full((3, 5), 3.14) 
print(a, a.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] float64


# empty

지정된 모양의 Array 생성

각 원소는 '초기화되지않은 값'으로 채워짐

for문을 사용하여 배열의 각 요소에 단일 값을 할당하여 사용

In [9]:
a = np.empty(5) 

for i in range(5):
    a[i] = 7 # 각 원소를 7로 채워줌
print(a)

[7. 7. 7. 7. 7.]


In [10]:
b = np.empty((3, 4))
print(b, b.dtype)
# 7로 채워진 이유는 앞의 연산에서 초기화되지 않은 값이기때문

[[2.01482500e-316 2.84612167e-316 3.95252517e-323 2.84612167e-316]
 [3.95252517e-323 2.84612167e-316 4.44659081e-323 0.00000000e+000]
 [2.84614697e-316 2.84614697e-316 2.84614697e-316 0.00000000e+000]] float64


# zeros_like

Array의 shape 크기만큼 0값으로 채워 Array 반환

In [11]:
a = np.array([1, 3, 5, 7, 9])

In [12]:
b = np.zeros_like(a) # 원래 값 대신 0으로 채워져 반환
print(b, b.dtype)

[0 0 0 0 0] int64


In [13]:
a = np.array([1.41, 2.72, 3.14])
b = np.zeros_like(a)
print(b, b.dtype) # 값은 변해도 type은 그대로 상속 받음

[0. 0. 0.] float64


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
b = np.zeros_like(a)
print(b, b.dtype)

[[0 0 0]
 [0 0 0]] int64


# ones_like

Array의 shape 크기만큼 1값으로 채워 Array 반환

In [16]:
a = np.array([1, 3, 5, 7, 9])

In [17]:
b = np.ones_like(a)
b

array([1, 1, 1, 1, 1])

In [18]:
a = np.array([1.41, 2.72, 3.14])

In [19]:
b = np.ones_like(a)
b

array([1., 1., 1.])

In [20]:
b = np.ones_like(a, dtype=np.int64)
b

array([1, 1, 1])

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
b = np.ones_like(a)

# full_like

Array의 shape 크기만큼 0값으로 채워 Array 반환

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
b = np.full_like(a, 7) # 채울 값을 7로 설정
b

array([[7, 7, 7],
       [7, 7, 7]])

In [25]:
b = np.full_like(a, 7, dtype=np.float64)
b

array([[7., 7., 7.],
       [7., 7., 7.]])

In [26]:
a = np.array([1.41, 2.72, 3.14])

In [27]:
b = np.full_like(a, 5)
b

array([5., 5., 5.])

In [28]:
b = np.full_like(a, 5, dtype=np.int64)
b

array([5, 5, 5])

# empty_like

Array의 shape 크기만큼 초기화되지 않은 값으로 채워 Array 반환

In [29]:
a = np.array([1, 3, 5])
a

array([1, 3, 5])

In [30]:
b = np.empty_like(a) 
b # a의 형태를 따르나 쓰레기값으로 채워져있음

array([4609028894647239311, 4613307314293241283, 4614253070214989087])

In [31]:
a = np.array([1.41, 2.72, 3.14])

In [32]:
b = np.empty_like(a)
b

array([2.1469911e-316, 0.0000000e+000, 0.0000000e+000])

In [33]:
b = np.empty_like(a, dtype=np.int64)
b

array([43455584,        0,        0])

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
b = np.empty_like(a)
b

array([[4619567317775286272, 4619567317775286272, 4619567317775286272],
       [4619567317775286272, 4619567317775286272, 4619567317775286272]])

In [36]:
b = np.empty_like(a, dtype=np.float64)

for i in range(2):
    b[i] = 8 # 각 원소값을 8로 지정
print(b)

[[8. 8. 8.]
 [8. 8. 8.]]


# fromfunction

함수 형식을 가져와 Array 생성

Array의 형태는 전적으로 함수에 의해 결정된다

In [37]:
I = np.fromfunction(lambda i, j: i == j, (5, 5)) # 5x5 형태 생성
I

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [38]:
a = np.fromfunction(lambda i, j: i + j, (5, 5), dtype=np.int64)
a

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [39]:
a = np.fromfunction(lambda i, j: 10*i + j, (3, 5), dtype=np.int64)
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])