In [14]:
import numpy as np

# save, load

Array 데이터를 외부 파일로 저장(save), 외부 파일을 배열로 불러오는(load)하는 방법

np.save 
: 1개의 배열을 NumPy format의 바이너리 파일로 저장


np.load
: np.save()로 저장된 *.npy 파일을 배열로 불러오기


In [15]:
# 아래 스크립트 파일을 *.npy로 저장
x = np.arange(100).reshape(10, 10)
np.save('test', x)

In [16]:
x = np.load('test.npy')
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# savz

여러개의 배열을 1개의 압축되지 않은 *.npz 포맷 파일로 저장



In [17]:
x = np.array([1, 3, 5, 7, 9])
y = np.linspace(0, 1, 11)
z = np.arange(100).reshape(10, 10)

np.savez('test', x=x, y=y, z=z) # 스크립트 파일을 *.npz로 저장

In [18]:
npzfile = np.load('test.npz') # np.savez()로 저장된 *.npz 파일을 배열로 불러옴

x = npzfile['x']
y = npzfile['y']
z = npzfile['z']

print(x)
print(y)
print(z)

[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# savetxt, loadtxt

np. savetxt
: 여러개의 배열을 텍스트 파일로 저장

np.loadtext 
: 텍스트 파일을 배열로 불러오기


In [19]:
x = np.arange(100).reshape(10, 10)
np.savetxt('test.txt', x) #  스크립트 파일을 *.txt로 저장하고 실행

In [20]:
x = np.loadtxt('test.txt')
print(x)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]
