# Basic Math Operations

Array의 기본 연산은 같은 위치의 각 원소간에 연산이다


In [23]:
import numpy as np

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b = np.array([[6, 5, 4], [3, 2, 1]])
b

array([[6, 5, 4],
       [3, 2, 1]])

In [26]:
# +
a + b

array([[7, 7, 7],
       [7, 7, 7]])

In [27]:
# -
a - b

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [28]:
# *
a * b

array([[ 6, 10, 12],
       [12, 10,  6]])

In [29]:
# /
a / b

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

In [30]:
# **
a ** b

array([[ 1, 32, 81],
       [64, 25,  6]])

In [31]:
# //
a // b

array([[0, 0, 0],
       [1, 2, 6]])

In [32]:
# %
a % b

array([[1, 2, 3],
       [1, 1, 0]])

# Broadcasting
array의 브로드 캐스트는
위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,

numpy에서는 브로드캐스트라는 기능을 제공

브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것

서로 크기가 다른 arr1과 arr3의 연산이 가능



이때, 연산은 각 array의 같은 인덱스 위치의 요소간 연산값 출력


아래 예제의 연산결과를 살펴보면 

arr3이 [7,8,9] 에서 [[7,8,9],[7,8,9]]로 확장되어 계산되었음을 확인할 수 있음


In [33]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [35]:
arr3 = np.array([7,8,9])
print(arr3)
print(arr3.shape)

[7 8 9]
(3,)


In [36]:
arr1 + arr3

array([[ 8, 10, 12],
       [11, 13, 15]])

In [37]:
arr1 - arr3

array([[-6, -6, -6],
       [-3, -3, -3]])

In [38]:
arr1 * arr3

array([[ 7, 16, 27],
       [28, 40, 54]])

하나의 array에 스칼라 연산도 가능

In [39]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]])

# Matrix Multiplication

In [45]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [46]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [47]:
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [48]:
d = np.matmul(a,b)
d

array([[19, 22],
       [43, 50]])

In [49]:
e = np.dot(a, b)
e

array([[19, 22],
       [43, 50]])

In [50]:
f = a.dot(b)
f

array([[19, 22],
       [43, 50]])

# Inner Product

In [51]:
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [52]:
c = np.matmul(a, b)
c

array([[19, 22],
       [43, 50]])

In [54]:
d = np.dot(a, b)
d

array([[19, 22],
       [43, 50]])

In [55]:
e = a.dot(b)
e

array([[19, 22],
       [43, 50]])

# Square, Square Root

In [56]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [57]:
y = np.square(x)
y

array([ 1,  4,  9, 16])

In [58]:
z = np.sqrt(x)
z

array([1.        , 1.41421356, 1.73205081, 2.        ])

# Sum

In [59]:
x.sum()

10

In [60]:
np.sum(x)

10

In [61]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [65]:
b = a.sum()
b

21

In [66]:
c = a.sum(axis=0)
c

array([5, 7, 9])

In [67]:
e = a.sum(axis=1)
e

array([ 6, 15])