# dtype 데이터형 확인 (Python 3.6.7 실행)


**numpy에서 사용되는 자료형 종류**

(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미)

부호가 있는 정수 int(8, 16, 32, 64)

부호가 없는 정수 uint(8 ,16, 32, 54)

실수 float(16, 32, 64, 128)

복소수 complex(64, 128, 256)

In [ ]:
import numpy as np

In [ ]:
# array 자료형 확인 
a = np.array([1, 3, 5, 7, 9])
a.dtype

dtype('int64')

In [ ]:
b = np.array([-1, -3, -5, -7, -9], np.int16)
b.dtype

dtype('int16')

In [ ]:
c= np.array([1, 3, 5, 7, 9], np.uint16)
c.dtype

dtype('uint16')

In [ ]:
d= np.array([1,2,3,3.5,4])
d.dtype

dtype('float64')

In [ ]:
e = np.array(2.718281828459045 + 3.141592653589793j, np.complex64)
e.dtype

dtype('complex64')

# Iterating (배열 반복)

1D Array

In [ ]:
x = np.arange(11)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Python의 for 반복문 이용
for i in x:
    print(i)

0
1
4
9
16
25
36
49
64
81
100


2D Array

n차원 배열의 각각의 개별 요소 접근 방법 3가지
1. 차원 수 만큼의 중첩 for문 이용해 접근
2. reshape(-1)로 평탄화 (1차원 배열 생성) 후 접근
3. nditer() 함수로 다차원 배열의 원소(스칼라)에 바로 접근 가능

In [ ]:
x = np.arange(10, 22).reshape(3, 4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
# Python의 for 반복문. 중첩 없을 경우
for row in x:
        print(row)

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [ ]:
# n차원 배열일 경우, n-1 차원이 for 반복문을 각각 통과함
for row in x:
        for i in row:
            print(i)

10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
# reshape(-1)로 평탄화
newX = x.reshape(-1)
for row in newX:
        print(row)

10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
# nditer()
for i in np.nditer(x):
  print(i)

10
11
12
13
14
15
16
17
18
19
20
21
