#**Numpy**

Numpy는 Numerical + Python의 합성어로서, c언어로 구현된 수치해석용 파이썬 라이브러리

ndarray 클래스(다차원의 배열 자료구조 클래스)를 지원하여 

행렬이나 대규모 다차원 연산을 쉽게 처리하게 해준다

데이터 분석 라이브러리인 pandas와 matplotlib의 기반으로 사용되기도 함


In [1]:
import numpy as np
# 넘파이 패키지 임포트는 관습적으로 'np'로 임포트함

#  Array

Numpy에서는 Array(배열) 단위로 데이터 관리, 연산함

Array는 Python List와 비슷하지만, C언어의 배열처럼 연속적인 메모리 배치를 가지기에

1. 모든 원소가 같은 자료형이여야 함

2. 원소의 갯수 변경 불가

List에 비해 제약이 있지만 원소에 대한 접근과 반복문 실행이 빠르다

In [2]:
# array 정의
data1 = [1,2,3,4,5]
print(data1, type(data1)) # python list

arr1 = np.array(data1)# python의 list 활용하여 생성한 array
print(arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# list를 바로 넣어 생성
arr2 = np.array([1,2,3,3,5,4])
print(arr2, type(arr2))

[1 2 3 3 5 4] <class 'numpy.ndarray'>


In [4]:
# 2차원 array 생성. list의 list를 사용하면 쉽게 생성 가능
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]]) # 4 x 3 array
print(arr3)
print('row: ',len(arr3)) # arr3의 행의 갯수
print('column: ',len(arr3[0]))# arr3의 열의 갯수

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
row:  4
column:  3


In [5]:
# 3차원 array 생성.list의 list의 list 사용
arr4 = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) # 2 x 3 x 4 array
print(arr4)
print('depth: ',len(arr4)) # 깊이
print('row: ',len(arr4[0])) # 행
print('column: ',len(arr4[0][0])) # 열

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
depth:  2
row:  3
column:  4


# ndim 배열의 차원 

ndim은 array dimension(배열의 차원)을 의미

In [6]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
1
2
3


In [7]:
arr5 = np.array([[[[[[1],[2]]],[[[3],[4]]]]],[[[[[5],[6]]],[[[7],[8]]]]]])
print(arr5.ndim)

6
