# Array Operations 

linspace() 

transpose() 

concatenate()

r_()

c_()

hstack()

vstack()

np.zeros() 

np.ones()

np.full()

In [ ]:
import numpy as np

# linspace 

구간 내 숫자를 균일한 간격으로 채우기.

인자로 구간 시작점, 끝점, 구간 내 숫자 개수 3가지를 준다


In [ ]:
 a = np.linspace(0, 1, 11)
 a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
a = np.linspace(0, 1)
a # 구간 내 숫자 개수를 인자로 넣지 않을 경. 50개

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
# endpoint = False 끝점을 포함하지 않고 싶을 경우
a = np.linspace(0, 1, 11,endpoint = False)
a

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

In [ ]:
# retstep = True 숫자 사이의 간격이 얼마인지에 대한 값을 같이 반환
a = np.linspace(0, 1, 11,retstep = True)
a

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), 0.1)

# transpose

입력 배열의 축을 반전시키거나 입력 배열을 전치함

인자로 배열, axis(축의 순서 지정,option)을 가짐

n차원 배열은 전치 반환이되지만 1차원 배열은 사용해도 아무 변화 없음

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = a.transpose()
b # a Array의 전치버전 반환

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b = a.T # transpose의 다른 표현
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 1D Array에 적용-> 메서드 통과 후에도 변화없음
a = np.array([2,3,4])
b = a.transpose()
b

array([2, 3, 4])

In [ ]:
# axis 축의 순서 지정.  순열을 포함하는 튜플 또는 목록을 2번째 인자로 넣음
a = np.ones((1, 2, 3))
print(a.shape)

b = np.transpose(a,(1, 0, 2))
print(b.shape)

(1, 2, 3)
(2, 1, 3)


# concatenate

여러 Array를 하나로 합칠때 사용

인자로 합칠 두 Array와 axis(option) 받음

axis 값을 조절하여 어떤 축을 기준으로 배열을 합칠지 정할 수 있다

In [ ]:
a = np.array([[1, 2],[3, 4]])
print(a)
b = np.array([[5, 6], [7, 8], [9, 10]])
print(b)

[[1 2]
 [3 4]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
c = np.concatenate((a, b), axis = 0)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
d = np.concatenate((a, b.T), axis = 1)
d

array([[ 1,  2,  5,  7,  9],
       [ 3,  4,  6,  8, 10]])

In [ ]:
e = np.concatenate((a, b), axis = None)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
d = np.concatenate((a, b), axis=1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# r_

위에서 아래(세로 방향)로 Array 합치기

1D Array에 사용하면 단순히 두 배열을 합치는 기능

함수( ) 를 사용하지 않고 연산자[ ]사용 주의

In [ ]:
# 1D Array
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6, 7])
print(b)

[1 2 3]
[4 5 6 7]


In [ ]:
c = np.r_[a, b] # 함수( ) 를 사용하지 않고 연산자[ ]사용 주의
c

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c = np.r_[4, a, 5]
c

array([4, 1, 2, 3, 5])

In [ ]:
# 2D Array
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
c = np.r_[a, b]
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
d = np.r_[b, a]
d

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

# c_

왼쪽에서 오른쪽(가로 방향)으로 Array 합치기

함수( ) 를 사용하지 않고 연산자[ ]사용 주의

In [ ]:
# 1D Array
a = np.array([1, 2, 3, 4])
print(a)
b = np.array([4, 5, 6, 7])
print(b)

[1 2 3 4]
[4 5 6 7]


In [ ]:
c = np.c_[a, b] # 원소 갯수가 같을 때만 사용 가능 
c

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [ ]:
c = np.c_[[a],[b]] # 각자 []처리하면 원소 갯수 상관 없음
c

array([[1, 2, 3, 4, 4, 5, 6, 7]])

In [ ]:
c = np.c_[4, [a], 5]
c

array([[4, 1, 2, 3, 4, 5]])

In [ ]:
# 2D Array
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
c = np.c_[a, b] # 따로 []를 하지 않았을 경우, 열 끼리 합침 
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
c = np.c_[[a],[b]] # 각자 []를 한 경우 하나로 합침. 리스트의 리스트로 출력
c

array([[[1, 2, 5, 6],
        [3, 4, 7, 8]]])

hstack

배열 가로로 결합

기본적으로 axis = 0 

vstack

배열 세로로 결합


기본적으로 axis = 1

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = [7, 8, 9]
print(a, type(a))
print(b, type(b))
print(c, type(c))

[1 2 3] <class 'numpy.ndarray'>
[4 5 6] <class 'numpy.ndarray'>
[7, 8, 9] <class 'list'>


In [ ]:
# 배열과 배열 결합
d = np.hstack((a, b)) 
d

array([1, 2, 3, 4, 5, 6])

In [ ]:
e = np.vstack((a, b)) 
e

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 배열과 리스트 결합도 가능
f = np.hstack((a, c))
f

array([1, 2, 3, 7, 8, 9])

In [ ]:
g = np.vstack((a, c))
g

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# 3개 이상 배열 결합
h = np.hstack((a, b, c))
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
i = np.vstack((a, b, c))
i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])