# shape 배열의 크기

array의 크기 반환

shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인 가능


In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [ ]:
# array 형태(크기)확인 (행 갯수, 열 갯수)
arr1.shape 
# 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다

(5,)

In [ ]:
arr2.shape
# 2차원의 데이터이며 3 * 3 크기를 갖고 있음을 알 수 있다

(3, 3)

#  reshape 배열과 차원(행,열) 변형

np.reshape(변경할 배열, (행,열))  

배열.reshape((행,열))

현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우 많이 활용

In [ ]:
# 2차원 변환
a = np.array([1,2,3,4,5,6,7,8])

b = np.reshape(a,(4,2))
c = np.reshape(a,(2,4))

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 3차원 변환
a = np.arange(1,13)
b = a. reshape(2,2,3) 
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

reshape에서 -1의 의미

reshape()의 -1은 변경될 배열의 '-1'위치의 차원은 원래 배열의 길이와 남은 차원으로부터 추정해서 알아서 지정하라는 뜻

즉, 행의 위치에 -1을 넣고 열의 값만 지정하면 변환될 행의 수는 알아서 자동 재배열이 된다

In [ ]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 행 위치에 -1을 넣을 경우
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# 열 위치에 -1을 넣을 경우
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# size 전체 원소의 갯수 반환

In [ ]:
arr1 = np.arange(1,7)
arr1.size

6

In [ ]:
arr2 = arr1.reshape(2,-1)
arr2.size
# arr1과 arr2의 차원이 달라도 전체 원소의 수는 같으므로 같은 값 나타남

6

In [ ]:
arr3 = np.arange(20)
arr3.size

20